services:
  PreprocessingService:
    container_name: "PreprocessingService"
    image: "michalmusil/tirecode-evaluation-preprocessing:latest"
    volumes:
      - preprocessing-volume:/app/models
    environment:
      OTEL_SERVICE_NAME: "PreprocessingService"
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_Exporter_Endpoint}
      OTEL_EXPORTER_OTLP_HEADERS: ${OTEL_Exporter_Headers}
      OTEL_EXPORTER_OTLP_PROTOCOL: ${OTEL_Exporter_Protocol}
      OTEL_RESOURCE_ATTRIBUTES: ${OTEL_Resource_Attributes}
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8080"
    restart: unless-stopped
  PreprocessingPythonService:
    container_name: "PreprocessingPythonService"
    image: "michalmusil/tirecode-evaluation-preprocessing-python:latest"
    restart: unless-stopped
  OcrService:
    container_name: "OcrService"
    image: "michalmusil/tirecode-evaluation-recognition:latest"
    environment:
      OTEL_SERVICE_NAME: "OcrService"
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_Exporter_Endpoint}
      OTEL_EXPORTER_OTLP_HEADERS: ${OTEL_Exporter_Headers}
      OTEL_EXPORTER_OTLP_PROTOCOL: ${OTEL_Exporter_Protocol}
      OTEL_RESOURCE_ATTRIBUTES: ${OTEL_Resource_Attributes}
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      ApiKeys__Gemini: ${ApiKeys__Gemini}
      ApiKeys__GeminiFineTuned: ${ApiKeys__GeminiFineTuned}
      ApiKeys__AzureAiVision: ${ApiKeys__AzureAiVision}
      ApiKeys__Mistral: ${ApiKeys__Mistral}
      ApiKeys__OpenAi: ${ApiKeys__OpenAi}
      ApiKeys__OpenAiFineTuned: ${ApiKeys__OpenAiFineTuned}
      ApiKeys__RunPod: ${ApiKeys__RunPod}
      ApiKeys__OpenRouter: ${ApiKeys__OpenRouter}
      ApiKeys__GcpJsonCredentials: ${ApiKeys__GcpJsonCredentials}
      HTTP_PORTS: "8080"
    restart: unless-stopped
  OcrPythonService:
    container_name: "OcrPythonService"
    image: "michalmusil/tirecode-evaluation-recognition-python:latest"
    restart: unless-stopped
  PostprocessingService:
    container_name: "PostprocessingService"
    image: "michalmusil/tirecode-evaluation-postprocessing:latest"
    environment:
      OTEL_SERVICE_NAME: "PostprocessingService"
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_Exporter_Endpoint}
      OTEL_EXPORTER_OTLP_HEADERS: ${OTEL_Exporter_Headers}
      OTEL_EXPORTER_OTLP_PROTOCOL: ${OTEL_Exporter_Protocol}
      OTEL_RESOURCE_ATTRIBUTES: ${OTEL_Resource_Attributes}
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8080"
    restart: unless-stopped
  DbMatcherService:
    container_name: "DbMatcherService"
    image: "michalmusil/tirecode-evaluation-dbmatcher:latest"
    environment:
      OTEL_SERVICE_NAME: "DbMatcherService"
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_Exporter_Endpoint}
      OTEL_EXPORTER_OTLP_HEADERS: ${OTEL_Exporter_Headers}
      OTEL_EXPORTER_OTLP_PROTOCOL: ${OTEL_Exporter_Protocol}
      OTEL_RESOURCE_ATTRIBUTES: ${OTEL_Resource_Attributes}
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8080"
      RemoteTireDbAddress: ${RemoteTireDbAddress}
      RemoteManufacturerDbAddress: ${RemoteManufacturerDbAddress}
    restart: unless-stopped
  EvaluationTool:
    container_name: "EvaluationTool"
    image: "michalmusil/tirecode-evaluation-service:latest"
    depends_on:
      - EvaluationDb
    environment:
      OTEL_SERVICE_NAME: "EvaluationTool"
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_Exporter_Endpoint}
      OTEL_EXPORTER_OTLP_HEADERS: ${OTEL_Exporter_Headers}
      OTEL_EXPORTER_OTLP_PROTOCOL: ${OTEL_Exporter_Protocol}
      OTEL_RESOURCE_ATTRIBUTES: ${OTEL_Resource_Attributes}
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8080"
      services__PreprocessingService__http__0: "http://PreprocessingService:8080"
      services__OcrService__http__0: "http://OcrService:8080"
      services__PostprocessingService__http__0: "http://PostprocessingService:8080"
      services__DbMatcherService__http__0: "http://DbMatcherService:8080"
      services__OcrPythonService__http__0: "http://OcrPythonService:10100"
      services__PreprocessingPythonService__http__0: "http://PreprocessingPythonService:10200"
      ConnectionStrings__evaluationdb: "Host=EvaluationDb;Database=evaluationdb;Username=${DB_USER};Password=${DB_PASSWORD}"
      Jwt__Secret: ${Jwt__Secret}
      InitialUserCredentials__Username: ${InitialUserCredentials__Username}
      InitialUserCredentials__Password: ${InitialUserCredentials__Password}
    ports:
      - target: 8080
        published: 10006
      - target: 8443
        published: 10007
    restart: unless-stopped
  EvaluationToolFrontend:
    container_name: "EvaluationToolFrontend"
    image: "michalmusil/tirecode-evaluation-service-fe:latest"
    environment:
      EVALUATION_VITE_PROXY_URL: "http://EvaluationTool:8080"
    ports:
      - target: 80
        published: 10008
    restart: unless-stopped
  EvaluationDb:
    container_name: "EvaluationDb"
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: evaluationdb
    volumes:
      - postgres-data:/var/lib/postgresql
volumes:
  preprocessing-volume:
    driver: local
  postgres-data:
    driver: local