// <auto-generated />
using System;
using AiPipeline.Orchestration.Runner.Infrastructure.Common.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiPipeline.Orchestration.Runner.Infrastructure.Migrations
{
    [DbContext(typeof(OrchestrationRunnerDbContext))]
    partial class OrchestrationRunnerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiPipeline.Orchestration.Runner.Domain.FileAggregate.File", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FileStorageScope")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("AiPipeline.Orchestration.Runner.Domain.NodeTypeAggregate.NodeProcedure", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InputSchema")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NodeTypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutputSchema")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NodeTypeId");

                    b.ToTable("NodeProcedure");
                });

            modelBuilder.Entity("AiPipeline.Orchestration.Runner.Domain.NodeTypeAggregate.NodeType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("NodeTypes");
                });

            modelBuilder.Entity("AiPipeline.Orchestration.Runner.Domain.PipelineResultAggregate.PipelineResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PipelineId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PipelineResults");
                });

            modelBuilder.Entity("AiPipeline.Orchestration.Runner.Domain.PipelineResultAggregate.PipelineStepResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NodeProcedureId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Result")
                        .HasColumnType("text");

                    b.Property<Guid>("ResultId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("WasSuccessful")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ResultId");

                    b.ToTable("PipelineStepResult");
                });

            modelBuilder.Entity("AiPipeline.Orchestration.Runner.Domain.NodeTypeAggregate.NodeProcedure", b =>
                {
                    b.HasOne("AiPipeline.Orchestration.Runner.Domain.NodeTypeAggregate.NodeType", null)
                        .WithMany("_availableProcedures")
                        .HasForeignKey("NodeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiPipeline.Orchestration.Runner.Domain.PipelineResultAggregate.PipelineStepResult", b =>
                {
                    b.HasOne("AiPipeline.Orchestration.Runner.Domain.PipelineResultAggregate.PipelineResult", null)
                        .WithMany("_stepResults")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiPipeline.Orchestration.Runner.Domain.NodeTypeAggregate.NodeType", b =>
                {
                    b.Navigation("_availableProcedures");
                });

            modelBuilder.Entity("AiPipeline.Orchestration.Runner.Domain.PipelineResultAggregate.PipelineResult", b =>
                {
                    b.Navigation("_stepResults");
                });
#pragma warning restore 612, 618
        }
    }
}
